// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZRK2aATy5gwgPHha6w7BWwJKp5UEOcc',
    appId: '1:1030809244653:web:78e7841ae775d7a0914de4',
    messagingSenderId: '1030809244653',
    projectId: 'supabasenotification',
    authDomain: 'supabasenotification.firebaseapp.com',
    storageBucket: 'supabasenotification.firebasestorage.app',
    measurementId: 'G-P51ESCSBJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPbX0xTXR6Y8eaenqnfVsJIvlQuolhZY',
    appId: '1:1030809244653:android:0c61b8a15b1eceb5914de4',
    messagingSenderId: '1030809244653',
    projectId: 'supabasenotification',
    storageBucket: 'supabasenotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlVBrEgAU5AU9iSJCv4aVTGkjhZCdA4Y',
    appId: '1:1030809244653:ios:6a665b375470e96c914de4',
    messagingSenderId: '1030809244653',
    projectId: 'supabasenotification',
    storageBucket: 'supabasenotification.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMlVBrEgAU5AU9iSJCv4aVTGkjhZCdA4Y',
    appId: '1:1030809244653:ios:6a665b375470e96c914de4',
    messagingSenderId: '1030809244653',
    projectId: 'supabasenotification',
    storageBucket: 'supabasenotification.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpZRK2aATy5gwgPHha6w7BWwJKp5UEOcc',
    appId: '1:1030809244653:web:f32cc389cd45e59c914de4',
    messagingSenderId: '1030809244653',
    projectId: 'supabasenotification',
    authDomain: 'supabasenotification.firebaseapp.com',
    storageBucket: 'supabasenotification.firebasestorage.app',
    measurementId: 'G-YB1Z8KQBF2',
  );
}
